name: testing
on:
    - push
    - workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout"
              run: |
                echo "Checking out the repository..."
                echo "${{ github.repository }}"
                git clone "https://github.com/${{ github.repository }}.git"

